export const STATUS_LABELS = {
  active: 'نشط',
  inactive: 'غير نشط',
  pending: 'قيد الانتظار',
  approved: 'معتمد',
  montage: 'التجهيز',
  printing: 'الطباعة',
  finishing: 'التشطيب',
  completed: 'مكتمل',
  shipped: 'تم الشحن',
  delivered: 'تم التسليم',
  cancelled: 'ملغى',
  'in-progress': 'قيد التنفيذ',
  'in-stock': 'متوفر',
  'low-stock': 'مخزون منخفض',
  'out-of-stock': 'نفد المخزون',
}

export const MATERIAL_TYPE_LABELS = {
  paper: 'ورق',
  ink: 'حبر',
  plate: 'بليت',
  chemical: 'كيماويات',
  glue: 'لاصق',
  other: 'أخرى',
}

export const TRANSACTION_TYPE_LABELS = {
  purchase: 'شراء',
  consumption: 'استهلاك',
  adjustment: 'تعديل',
  return: 'مرتجع',
}

export const ar = {
  common: {
    search: 'بحث...',
    addNew: 'إضافة جديد',
    edit: 'تعديل',
    delete: 'حذف',
    save: 'حفظ',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    actions: 'إجراءات',
    status: 'الحالة',
    loading: 'جاري التحميل...',
    close: 'إغلاق',
    tryAgain: 'إعادة المحاولة',
    noData: 'لا توجد بيانات',
    noDataDescription: 'لا توجد عناصر لعرضها.',
    errorTitle: 'حدث خطأ ما',
    errorDescription: 'حدث خطأ أثناء تحميل البيانات. يرجى المحاولة مرة أخرى.',
    confirmTitle: 'هل أنت متأكد؟',
    confirmDescription: 'لا يمكن التراجع عن هذا الإجراء.',
    deleteItemTitle: 'حذف العنصر',
    deleteItemDescription: 'هل أنت متأكد من حذف هذا العنصر؟ لا يمكن التراجع عن هذا الإجراء.',
    showing: 'عرض',
    of: 'من',
    page: 'صفحة',
    fromLastMonth: 'من الشهر الماضي',
    units: 'وحدة',
    low: 'منخفض',
    chartPlaceholder: 'مكان الرسم البياني',
    collapse: 'طي',
    admin: 'المسؤول',
    manager: 'مدير',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    city: 'المدينة',
    address: 'العنوان',
    company: 'الشركة',
    created: 'تاريخ الإنشاء',
    updated: 'آخر تحديث',
    selectStatus: 'اختر الحالة',
    exportAll: 'تصدير الكل',
    downloadReport: 'تحميل التقرير',
    reportPeriod: 'فترة التقرير',
    daily: 'يومي',
    weekly: 'أسبوعي',
    monthly: 'شهري',
    yearly: 'سنوي',
    saveChanges: 'حفظ التغييرات',
    savePreferences: 'حفظ التفضيلات',
    saveNotifications: 'حفظ الإشعارات',
    currency: 'ر.س',
    view: 'عرض',
    notes: 'ملاحظات',
    statusChanged: 'تم تغيير الحالة إلى',
    notesUpdated: 'تم تحديث الملاحظات',
    orderNumberRequired: 'رقم الطلب المطلوب',
    companyRequired: 'اختر الشركة',
    productRequired: 'اختر المنتج',
    quantityRequired: 'الكمية يجب أن تكون أكبر من صفر',
    orderDateInvalid: 'تاريخ الطلب غير صالح',
    expectedDeliveryDateInvalid: 'تاريخ التسليم المتوقع غير صالح',
  },
  shared: {
    addressPlaceholder: 'أدخل العنوان',
    notesPlaceholder: 'ملاحظات إضافية (اختياري)',
    managerName: 'اسم المدير',
    managerNamePlaceholder: 'أدخل اسم المدير',
    validation: {
      nameMin: 'الاسم مطلوب (حرفين على الأقل)',
      emailInvalid: 'البريد الإلكتروني غير صالح',
      phoneInvalid: 'رقم الهاتف غير صالح',
      typeRequired: 'نوع المادة مطلوب',
      unitRequired: 'الوحدة مطلوبة',
      minStockMin: 'الحد الأدنى يجب أن يكون 0 أو أكثر',
      managerNameMin: 'اسم المدير مطلوب (حرفين على الأقل)',
      managerNameMax: 'اسم المدير يجب ألا يتجاوز 100 حرف',
    },
  },
  nav: {
    dashboard: 'لوحة التحكم',
    companies: 'الشركات',
    suppliers: 'الموردون',
    materials: 'المواد',
    inventory: 'المخزون',
    products: 'المنتجات',
    purchases: 'المشتريات',
    productionOrders: 'أوامر الإنتاج',
    reports: 'التقارير',
    settings: 'الإعدادات',
  },
  dashboard: {
    title: 'لوحة التحكم',
    description: 'نظرة عامة على عمليات إدارة الطباعة',
    loading: 'جاري تحميل لوحة التحكم...',
    goodMorning: 'صباح الخير',
    goodAfternoon: 'مساء الخير',
    goodEvening: 'مساء الخير',
    welcomeBack: 'مرحباً بعودتك',
    totalCompanies: 'إجمالي الشركات',
    totalProducts: 'إجمالي المنتجات',
    materialsInStock: 'المواد في المخزون',
    lowStockMaterials: 'مواد مخزون منخفض',
    todaysProductionOrders: 'أوامر الإنتاج اليوم',
    completedOrders: 'الطلبات المكتملة',
    pendingOrders: 'الطلبات المعلقة',
    recentProductionOrders: 'أوامر الإنتاج الأخيرة',
    recentProductionOrdersDesc: 'آخر أوامر الإنتاج المسجلة في النظام',
    inventorySummary: 'ملخص المخزون',
    inventorySummaryDesc: 'نظرة سريعة على حالة المواد',
    totalMaterials: 'إجمالي المواد',
    lowStock: 'مخزون منخفض',
    recentlyPurchased: 'مشتريات حديثة',
    mostUsedMaterial: 'الأكثر استخداماً',
    recentActivities: 'النشاط الأخير',
    recentActivitiesDesc: 'آخر الأحداث والتحديثات',
    quickActions: 'إجراءات سريعة',
    quickActionsDesc: 'اختصارات للمهام الشائعة',
    newProductionOrder: 'أمر إنتاج جديد',
    addCompany: 'إضافة شركة',
    addMaterial: 'إضافة مادة',
    createPurchase: 'إنشاء شراء',
    chartsSection: 'التحليلات',
    chartsSectionDesc: 'رسوم بيانية توضيحية — قريباً',
    inventoryChart: 'رسم المخزون',
    productionChart: 'رسم الإنتاج',
    monthlyOrdersChart: 'الطلبات الشهرية',
    viewAll: 'عرض الكل',
    createdDate: 'تاريخ الإنشاء',
  },
  companies: {
    title: 'الشركات',
    description: 'إدارة شركات العملاء والشركاء التجاريين',
    search: 'بحث في الشركات...',
    add: 'إضافة شركة',
    addForm: 'إضافة شركة',
    editForm: 'تعديل شركة',
    viewTitle: 'تفاصيل الشركة',
    deleteTitle: 'حذف الشركة',
    deleteDescription: 'هل أنت متأكد من حذف هذه الشركة؟ لا يمكن التراجع عن هذا الإجراء.',
    name: 'اسم الشركة',
    namePlaceholder: 'أدخل اسم الشركة',
    productsCount: 'عدد المنتجات',
    emailPlaceholder: 'company@email.com',
    cityPlaceholder: 'أدخل المدينة',
    validation: {
      nameMin: 'يجب أن يكون الاسم حرفين على الأقل',
      emailInvalid: 'البريد الإلكتروني غير صالح',
      phoneRequired: 'رقم الهاتف مطلوب',
      cityMin: 'اسم المدينة مطلوب',
    },
  },
  suppliers: {
    title: 'الموردون',
    description: 'إدارة موردي المواد والمعدات',
    search: 'بحث في الموردين...',
    add: 'إضافة مورد',
    addForm: 'إضافة مورد',
    editForm: 'تعديل مورد',
    viewTitle: 'تفاصيل المورد',
    deleteTitle: 'حذف المورد',
    deleteDescription: 'هل أنت متأكد من حذف هذا المورد؟ لا يمكن التراجع عن هذا الإجراء.',
    name: 'اسم المورد',
    namePlaceholder: 'أدخل اسم المورد',
    materialsCount: 'عدد المواد',
    contact: 'جهة الاتصال',
    category: 'الفئة',
  },
  materials: {
    title: 'المواد',
    description: 'إدارة كتالوج المواد الخام والمستلزمات للطباعة',
    search: 'بحث في المواد...',
    add: 'إضافة مادة',
    addForm: 'إضافة مادة',
    editForm: 'تعديل مادة',
    viewTitle: 'تفاصيل المادة',
    deleteTitle: 'حذف المادة',
    deleteDescription: 'هل أنت متأكد من حذف هذه المادة؟ لا يمكن التراجع عن هذا الإجراء.',
    name: 'اسم المادة',
    namePlaceholder: 'أدخل اسم المادة',
    type: 'نوع المادة',
    selectType: 'اختر النوع',
    unit: 'الوحدة',
    unitPlaceholder: 'مثال: رزمة، لتر، كيلو',
    paperType: 'نوع الورق',
    weight: 'الوزن',
    width: 'العرض',
    height: 'الارتفاع',
    brightness: 'السطوع',
    color: 'اللون',
    inkTypes: 'أنواع الحبر',
    chemicalTypes: 'أنواع الكيماويات',
    minStock: 'الحد الأدنى للمخزون',
    currentStock: 'المخزون الحالي',
    description: 'الوصف',
    descriptionPlaceholder: 'وصف المادة (اختياري)',
    filterType: 'تصفية حسب النوع',
    filterStatus: 'تصفية حسب الحالة',
    allTypes: 'كل الأنواع',
    allStatuses: 'كل الحالات',
    variants: 'الأصناف',
    noVariantsToManage: 'لا توجد أصناف لإدارتها',
    paperManagement: 'إدارة الأوراق',
    addPaper: 'إضافة ورقة',
    noPapersYet: 'لا توجد أوراق حتى الآن',
    inkManagement: 'إدارة الأحبار',
    addInk: 'إضافة حبر',
    noInksYet: 'لا توجد أحبار حتى الآن',
    chemicalManagement: 'إدارة الكيماويات',
    addChemical: 'إضافة كيميائي',
    noChemicalsYet: 'لا توجد كيماويات حتى الآن',
  },
  inventory: {
    title: 'المخزون',
    description: 'تتبع حركات المستودع ومستويات المواد',
    search: 'بحث في الحركات...',
    material: 'المادة',
    quantity: 'الكمية',
    date: 'التاريخ',
    transactionType: 'نوع الحركة',
    reference: 'المرجع',
    unit: 'الوحدة',
    filterMaterial: 'تصفية حسب المادة',
    filterType: 'تصفية حسب النوع',
    dateFrom: 'من تاريخ',
    dateTo: 'إلى تاريخ',
    allMaterials: 'كل المواد',
    allTypes: 'كل الأنواع',
    totalMaterials: 'إجمالي المواد',
    lowStock: 'مخزون منخفض',
    outOfStock: 'نفد المخزون',
    recentPurchases: 'مشتريات حديثة',
    recentActivity: 'النشاط الأخير',
    recentActivityDesc: 'آخر حركات المخزون',
    transactions: 'حركات المخزون',
    transactionsDesc: 'سجل حركات الإدخال والإخراج',
    materialDetails: 'تفاصيل المادة',
    recentTransactions: 'آخر الحركات',
    selectMaterial: 'اختر المادة',
  },
  products: {
    title: 'المنتجات',
    description: 'إدارة منتجات الطباعة والأسعار',
    search: 'بحث في المنتجات...',
    add: 'إضافة منتج',
    addForm: 'إضافة منتج',
    editForm: 'تعديل منتج',
    viewTitle: 'تفاصيل المنتج',
    deleteTitle: 'حذف المنتج',
    deleteDescription: 'هل أنت متأكد من حذف هذا المنتج؟ لا يمكن التراجع عن هذا الإجراء.',
    productCode: 'رمز المنتج',
    productCodePlaceholder: 'أدخل رمز المنتج',
    productCodeRequired: 'رمز المنتج مطلوب',
    productName: 'اسم المنتج',
    productNamePlaceholder: 'أدخل اسم المنتج',
    productNameRequired: 'اسم المنتج مطلوب',
    companyName: 'الشركة',
    selectCompany: 'اختر الشركة',
    companyRequired: 'المورد مطلوب',
    category: 'الفئة',
    categoryPlaceholder: 'أدخل الفئة',
    categoryRequired: 'الفئة مطلوبة',
    status: 'الحالة',
    active: 'نشط',
    inactive: 'غير نشط',
    description: 'الوصف',
    descriptionPlaceholder: 'وصف المنتج (اختياري)',
  },
  purchases: {
    title: 'المشتريات',
    description: 'إدارة أوامر الشراء ومعاملات الموردين',
    search: 'بحث في المشتريات...',
    add: 'أمر شراء جديد',
    orderNumber: 'رقم الطلب',
    supplier: 'المورد',
    items: 'العناصر',
    total: 'الإجمالي (ر.س)',
    date: 'التاريخ',
  },
  productionOrders: {
    title: 'أوامر الإنتاج',
    description: 'تتبع وإدارة أوامر الإنتاج',
    search: 'بحث في أوامر الإنتاج...',
    add: 'أمر إنتاج جديد',
    createTitle: 'إنشاء أمر إنتاج جديد',
    createDescription: 'ملء التفاصيل لإنشاء أمر إنتاج جديد',
    editTitle: 'تعديل أمر الإنتاج',
    editDescription: 'تعديل تفاصيل الأمر الإنتاجي المحدد',
    orderNumber: 'رقم الطلب',
    product: 'المنتج',
    company: 'الشركة',
    quantity: 'الكمية',
    orderDate: 'تاريخ الطلب',
    dueDate: 'تاريخ التسليم المتوقع',
    status: 'الحالة',
    notes: 'ملاحظات',
    createdAt: 'تاريخ الإنشاء',
    updatedAt: 'آخر تحديث',
    confirmCancel: 'هل أنت متأكد من إلغاء هذا الأمر؟',
    cannotMoveBack: 'لا يمكن العودة إلى المرحلة السابقة',
    moveToNextStage: 'النقل إلى المرحلة التالية',
    goToPreviousStage: 'الانتقال إلى المرحلة السابقة',
    backToList: 'الرجوع إلى القائمة',
    createdSuccessfully: 'تم إنشاء الأمر بنجاح',
    updatedSuccessfully: 'تم تحديث الأمر بنجاح',
    deletedSuccessfully: 'تم حذف الأمر بنجاح',
    errorOccurred: 'حدث خطأ ما',
    filterStatus: 'تصفية حسب الحالة',
    filterCompany: 'تصفية حسب الشركة',
    filterDateRange: 'نطاق التاريخ',
    statusTimeline: ' timeline الحالة',
    progress: 'التقدم',
    ticketPreview: 'معاينة التذكرة',
    activityHistory: 'تاريخ النشاط',
    statusActions: 'إجراءات الحالة',
    statusPending: 'قيد الانتظار',
    statusApproved: 'معتمد',
    statusMontage: 'التجهيز',
    statusPrinting: 'الطباعة',
    statusFinishing: 'التشطيب',
    statusCompleted: 'مكتمل',
    statusShipped: 'تم الشحن',
    statusDelivered: 'تم التسليم',
    statusCancelled: 'ملغى',
  },
  reports: {
    title: 'التقارير',
    description: 'إنشاء وعرض تقارير الأعمال',
    sales: 'تقرير المبيعات',
    salesDesc: 'الإيرادات وأداء المبيعات',
    inventory: 'تقرير المخزون',
    inventoryDesc: 'مستويات المخزون والحركات',
    production: 'تقرير الإنتاج',
    productionDesc: 'إنجاز الطلبات والكفاءة',
    purchase: 'تقرير المشتريات',
    purchaseDesc: 'تحليل إنفاق الموردين',
  },
  settings: {
    title: 'الإعدادات',
    description: 'تكوين تفضيلات النظام',
    companyInfo: 'معلومات الشركة',
    companyInfoDesc: 'التفاصيل الأساسية للشركة للتقارير والمستندات',
    companyName: 'اسم الشركة',
    systemPreferences: 'تفضيلات النظام',
    systemPreferencesDesc: 'إعدادات التطبيق العامة',
    defaultCurrency: 'العملة الافتراضية',
    dateFormat: 'تنسيق التاريخ',
    lowStockThreshold: 'حد المخزون المنخفض',
    itemsPerPage: 'عناصر في الصفحة',
    notifications: 'الإشعارات',
    notificationsDesc: 'تكوين تفضيلات التنبيهات',
    lowStockAlerts: 'تنبيهات المخزون المنخفض',
    productionReminders: 'تذكيرات موعد تسليم أوامر الإنتاج',
    purchaseUpdates: 'تحديثات حالة أوامر الشراء',
  },
}
